const {test}=require('node:test');const assert=require('node:assert/strict');const {boot}=require('./userscript-helpers.cjs');
test('带原文依据的字段导入，教育经历分段、幂等、已有值和锁定字段保留',()=>{
 const {w}=boot('<input>');try{const v=w.ResumeProfileV2,p=v.createProfile('测试导入');const source='姓名：测试同学\n示例大学 甲专业 2020.09\n示例学院 乙专业 2022.09\n真实补充内容';p.singles.personal['personal.name']={value:'原姓名',locked:true};v.saveProfile(p);const fields=[{fieldId:'personal.name',value:'测试同学',evidence:'姓名：测试同学'},{fieldId:'education.school',record:'a',value:'示例大学',evidence:'示例大学 甲专业 2020.09'},{fieldId:'education.major',record:'a',value:'甲专业',evidence:'示例大学 甲专业 2020.09'},{fieldId:'education.startDate',record:'a',value:'2020-09-01',evidence:'示例大学 甲专业 2020.09'},{fieldId:'education.school',record:'b',value:'示例学院',evidence:'示例学院 乙专业 2022.09'},{fieldId:'education.major',record:'b',value:'乙专业',evidence:'示例学院 乙专业 2022.09'},{fieldId:'education.school',record:'c',value:'凭空大学',evidence:'无依据'}];const result=w.ResumeDocumentImport.importFields(p,{source,fields,custom:[{name:'补充字段',value:'真实补充内容',evidence:'真实补充内容'}]});assert.equal(result.profile.lists.education.length,2);assert.equal(result.profile.singles.personal['personal.name'].value,'原姓名');assert.equal(result.report.conflicts.length,1);assert.equal(result.report.rejected.length,1);assert.equal(result.profile.customFields.length,1);assert.ok(w.ResumeAnswerLibrary.all().find(x=>x.label==='补充字段'));const again=w.ResumeDocumentImport.importFields(result.profile,{source,fields,custom:[]});assert.equal(again.profile.lists.education.length,2);}finally{w.close();}
});
test('未配置 AI 可本地提取姓名电话邮箱；AI 路径隐藏手机号并拒绝无依据事实',async()=>{
 const {w}=boot('<input>');try{let sent='';const text='姓名：测试同学\n手机号：13800138000\n邮箱：test@example.com\n学校：示例大学';let r=await w.ResumeDocumentImport.extractFields(text);assert.equal(r.localOnly,true);assert.equal(r.fields.length,3);w.ResumeAI.isConfigured=()=>true;w.ResumeAI.chat=async messages=>{sent=messages[1].content;return JSON.stringify({fields:[{fieldId:'education.school',record:'a',value:'示例大学',evidence:'学校：示例大学'},{fieldId:'education.major',record:'a',value:'不存在专业',evidence:'学校：示例大学'}],custom:[]});};r=await w.ResumeDocumentImport.extractFields(text);assert.equal(sent.includes('13800138000'),false);assert.equal(r.fields.some(f=>f.value==='不存在专业'),false);assert.equal(r.fields.find(f=>f.fieldId==='contact.phone').value,'13800138000');}finally{w.close();}
});
test('知识提纯只存知识，原文保留、跨页面恢复、个人字段保持不变',async()=>{
 const {w}=boot('<input>');try{const before=JSON.stringify(w.ResumeProfileV2.activeProfile());w.ResumeAI.isConfigured=()=>true;w.ResumeAI.chat=async()=>JSON.stringify({knowledge:[{text:'示例项目：完成材料核对。',evidence:'项目完成了材料核对'},{text:'虚构结果',evidence:'不存在原文'}]});const refined=await w.ResumeDocumentImport.refine('项目完成了材料核对');assert.match(refined,/原文依据/);assert.equal(refined.includes('虚构结果'),false);const f=await w.ResumeFiles.addText('测试知识',refined,{originalText:'项目完成了材料核对',refined:true});assert.equal(JSON.stringify(w.ResumeProfileV2.activeProfile()),before);assert.equal(await w.ResumeFiles.getText(f.id),refined);const backup=w.ResumeStore.exportAll();const second=boot('<input>','https://another.example.test/',backup);try{assert.equal(await second.w.ResumeFiles.getText(f.id),refined);assert.ok((await second.w.ResumeFiles.search('材料核对')).includes('核对'));}finally{second.w.close();}}finally{w.close();}
});
test('知识库页面在解析后提供两个独立处理按钮，旧 JD 留存入口已移除',async()=>{
 const {w,roots}=boot('<label>姓名<input></label>');try{w.ResumeProfileEditor.show('files');let s=roots.profile;const inp=s.querySelector('input[type=file]');w.ResumeFiles.parse=async()=> '姓名：测试同学';Object.defineProperty(inp,'files',{value:[{name:'测试.pdf',size:100,type:'application/pdf'}]});inp.dispatchEvent(new w.Event('change'));await new Promise(r=>w.setTimeout(r,20));assert.ok(Array.from(s.querySelectorAll('button')).find(b=>b.textContent==='识别并存入字段库'));assert.ok(Array.from(s.querySelectorAll('button')).find(b=>b.textContent==='仅作为 AI 提纯知识库'));assert.equal(roots.ai.textContent.includes('存下本页 JD'),false);}finally{w.close();}
});

test('导入支持空技能对象，异步结果不会切换到旧简历',()=>{const {w}=boot('<input>');try{const v=w.ResumeProfileV2,target=v.createProfile('导入目标'),skill=w.ResumeFieldLibrary.all().find(x=>x.category==='skills').fieldId;target.skills[skill]={value:{desc:''},locked:false};v.saveProfile(target);const other=v.createProfile('当前简历');const result=w.ResumeDocumentImport.importFields(target,{source:'工具：示例工具',fields:[{fieldId:skill,value:'示例工具',evidence:'工具：示例工具'}],custom:[]});assert.equal(v.activeProfile().id,other.id);assert.equal(result.profile.skills[skill].value.desc,'示例工具');}finally{w.close();}});
