const fs=require('node:fs');
const modules=require('./modules.json');
// The bundle version is single-sourced from package.json so the popup's bridge check and the page
// bundle cannot drift apart. tests/version.test.cjs guards manifest.json and popup.js as well.
const version=require('../package.json').version;
const rules=JSON.stringify(JSON.parse(fs.readFileSync('extension/site-rules.json','utf8')));
const body=modules.map(p=>'// MODULE: '+p+'\n'+fs.readFileSync('extension/core/'+p,'utf8')).join('\n');
fs.writeFileSync('extension/engine.js', '// Generated by npm run build; edit core/ modules.\n'+
 'globalThis.ResumeEngineVersion='+JSON.stringify(version)+';\n'+
 'globalThis.ResumeSiteRules='+rules+';\n'+'globalThis.ResumeEngine={create(){\n"use strict";\n'+body+'\nreturn {version:ResumeEngineVersion,showResults,resultNotice,previewValue,scan,scanSelected,fillReviewed,finishSelected,prepare,prepareRecords,commitPendingAdd,fill,undo,run,debug:()=>lastRun,site:()=>siteAdapter.name,fieldIdForElement,elementOfField};\n}};\n');
